# GitHub Sponsors and funding platforms

github: [Volynskiy-Business]

patreon: psy-support

ko_fi: psy-support

custom:
  - https://www.buymeacoffee.com/psy-support
  - https://boosty.to/psy-support
  - https://paypal.me/psy-support
